'use client'

import { useEffect, useRef, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import useAuthStore, { getCustomerToken } from '@/lib/authStore'
import { API_URL, backendRequest } from '@/lib/backend'
import { toast } from '@/components/ui/ToastProvider'

const tabs = ['Overview', 'Orders', 'Account', 'Security', 'Devices']

export default function ProfilePage() {
  const router = useRouter()
  const { user, loading, logout } = useAuthStore()
  const [orders, setOrders] = useState([])
  const [tab, setTab] = useState('Overview')
  const [profile, setProfile] = useState({ name: '', phone: '' })
  const [password, setPassword] = useState({ currentPassword: '', newPassword: '', confirmPassword: '' })
  const [saving, setSaving] = useState(false)
  const [uploading, setUploading] = useState(false)
  const [reviewTarget, setReviewTarget] = useState(null)
  const [reviewForm, setReviewForm] = useState({ rating: 5, comment: '' })
  const [reviewing, setReviewing] = useState(false)
  const [sessions, setSessions] = useState([])
  const [sessionsLoading, setSessionsLoading] = useState(false)
  const fileRef = useRef(null)

  useEffect(() => { if (!loading && !user) router.replace('/login?returnTo=/profile') }, [loading, user, router])
  useEffect(() => { if (!user) return; const timeout = setTimeout(() => setProfile({ name: user.name || '', phone: user.phone || '' }), 0); backendRequest('/orders/mine?limit=100', { headers: authHeaders() }).then(({ data }) => setOrders(data)).catch((error) => toast('error', error.message, 'Unable to load account')); return () => clearTimeout(timeout) }, [user])
  useEffect(() => { if (tab !== 'Devices' || !user) return; let active = true; const timeout = setTimeout(() => { setSessionsLoading(true); backendRequest('/auth/sessions', { headers: authHeaders() }).then(({ data }) => { if (active) setSessions(data) }).catch((error) => toast('error', error.message, 'Unable to load devices')).finally(() => { if (active) setSessionsLoading(false) }) }, 0); return () => { active = false; clearTimeout(timeout) } }, [tab, user])

  if (loading || !user) return <div className="flex min-h-screen items-center justify-center bg-white"><span className="h-12 w-12 animate-spin rounded-full border-2 border-gray-200 border-t-black" /></div>

  const activeOrders = orders.filter((order) => !['cancelled', 'returned', 'delivered'].includes(order.status))
  const deliveredOrders = orders.filter((order) => order.status === 'delivered')
  const spent = orders.filter((order) => !['cancelled', 'returned'].includes(order.status)).reduce((sum, order) => sum + order.total, 0)
  const initials = user.name?.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase()

  const saveProfile = async (event) => {
    event.preventDefault(); setSaving(true)
    try { const { data } = await backendRequest('/auth/profile', { method: 'PATCH', headers: authHeaders(), body: JSON.stringify({ ...profile, photo: user.photo || '' }) }); useAuthStore.setState({ user: data }); toast('success', 'Your profile has been updated.', 'Profile saved') } catch (error) { toast('error', error.message, 'Update failed') } finally { setSaving(false) }
  }
  const uploadPhoto = async (file) => {
    if (!file) return
    setUploading(true)
    try { const body = new FormData(); body.append('image', file); const response = await fetch(`${API_URL}/uploads/profile-image`, { method: 'POST', headers: authHeaders(), body }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message || 'Image upload failed.'); const result = await backendRequest('/auth/profile', { method: 'PATCH', headers: authHeaders(), body: JSON.stringify({ ...profile, photo: payload.data.url }) }); useAuthStore.setState({ user: result.data }); toast('success', 'Your profile photo has been updated.', 'Photo updated') } catch (error) { toast('error', error.message, 'Upload failed') } finally { setUploading(false); if (fileRef.current) fileRef.current.value = '' }
  }
  const changePassword = async (event) => {
    event.preventDefault()
    if (password.newPassword.length < 8) return toast('warning', 'Your new password must contain at least 8 characters.', 'Password too short')
    if (password.newPassword !== password.confirmPassword) return toast('warning', 'New password and confirmation do not match.', 'Passwords do not match')
    setSaving(true)
    try { await backendRequest('/auth/password', { method: 'PATCH', headers: authHeaders(), body: JSON.stringify({ currentPassword: password.currentPassword, newPassword: password.newPassword }) }); setPassword({ currentPassword: '', newPassword: '', confirmPassword: '' }); toast('success', 'Your password has been changed securely.', 'Password updated') } catch (error) { toast('error', error.message, 'Password update failed') } finally { setSaving(false) }
  }
  const makeDefault = async (address) => { try { const { data } = await backendRequest(`/auth/addresses/${address._id}`, { method: 'PATCH', headers: authHeaders(), body: JSON.stringify({ isDefault: true }) }); useAuthStore.setState({ user: data }); toast('success', `${address.label} is now your default address.`, 'Address updated') } catch (error) { toast('error', error.message, 'Address update failed') } }
  const submitReview = async () => { if (reviewForm.comment.trim().length < 5) return toast('warning', 'Write at least 5 characters in your review.', 'Review incomplete'); setReviewing(true); try { await backendRequest('/reviews', { method: 'POST', headers: authHeaders(), body: JSON.stringify({ orderId: reviewTarget.order._id, itemIndex: reviewTarget.itemIndex, ...reviewForm }) }); toast('success', 'Your verified review is now published.', 'Thank you'); setReviewTarget(null); setReviewForm({ rating: 5, comment: '' }) } catch (error) { toast('error', error.message, 'Review could not be submitted') } finally { setReviewing(false) } }
  const loadSessions = async () => { setSessionsLoading(true); try { const { data } = await backendRequest('/auth/sessions', { headers: authHeaders() }); setSessions(data) } catch (error) { toast('error', error.message, 'Unable to load devices') } finally { setSessionsLoading(false) } }
  const endSession = async (session) => { try { await backendRequest(`/auth/sessions/${session._id}`, { method: 'DELETE', headers: authHeaders() }); if (session.isCurrent) { await logout(); router.replace('/login') } else { await loadSessions(); toast('success', 'The selected device has been signed out.', 'Session ended') } } catch (error) { toast('error', error.message, 'Unable to end session') } }

  return <main className="min-h-screen bg-[#f4f4f1] text-gray-950">
    <section className="border-b border-gray-200 bg-white"><div className="mx-auto max-w-7xl px-4 py-10 md:px-6"><div className="flex flex-col gap-7 md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-5"><div className="relative"><div className="flex h-24 w-24 items-center justify-center overflow-hidden rounded-3xl bg-black text-2xl font-black text-white shadow-xl">{user.photo ? <img src={user.photo} alt={user.name} className="h-full w-full object-cover" /> : initials}</div><button onClick={() => fileRef.current?.click()} disabled={uploading} className="absolute -bottom-2 -right-2 flex h-9 w-9 items-center justify-center rounded-full border-4 border-white bg-black text-sm text-white shadow-lg" aria-label="Upload profile photo">{uploading ? '…' : '↥'}</button><input ref={fileRef} hidden type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={(event) => uploadPhoto(event.target.files?.[0])} /></div><div><p className="text-[10px] font-black uppercase tracking-[.22em] text-gray-400">Customer account</p><h1 className="mt-1 text-3xl font-black tracking-tight text-black">{user.name}</h1><p className="mt-1 text-sm text-gray-500">{user.email}</p><span className="mt-3 inline-flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-black uppercase text-emerald-700"><span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />Active account</span></div></div><div className="flex gap-2"><Link href="/shop" className="rounded-xl border border-gray-300 bg-white px-5 py-3 text-xs font-black text-black">Continue shopping</Link><button onClick={async () => { await logout(); router.push('/') }} className="rounded-xl bg-black px-5 py-3 text-xs font-black text-white">Sign out</button></div></div><nav className="mt-9 flex gap-1 overflow-x-auto border-b border-gray-200">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={`shrink-0 border-b-2 px-5 py-3 text-xs font-black transition ${tab === item ? 'border-black text-black' : 'border-transparent text-gray-400 hover:text-black'}`}>{item}</button>)}</nav></div></section>

    <div className="mx-auto max-w-7xl px-4 py-8 md:px-6">
      {tab === 'Overview' && <div className="space-y-7"><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Stat label="Total orders" value={orders.length} /><Stat label="Active orders" value={activeOrders.length} /><Stat label="Delivered" value={deliveredOrders.length} /><Stat label="Total spent" value={`Rs. ${spent.toLocaleString()}`} /></div><div className="grid gap-6 lg:grid-cols-[1.4fr_.6fr]"><Panel title="Recent orders" action={<button onClick={() => setTab('Orders')} className="text-xs font-black underline">View all</button>}>{orders.length ? <div className="divide-y divide-gray-100">{orders.slice(0, 3).map((order) => <CompactOrder key={order._id} order={order} />)}</div> : <EmptyOrders />}</Panel><Panel title="Account details"><dl className="space-y-4 text-sm"><Detail label="Full name" value={user.name} /><Detail label="Email address" value={user.email} /><Detail label="Phone number" value={user.phone || 'Not added'} /><Detail label="Saved addresses" value={String(user.addresses?.length || 0)} /></dl><button onClick={() => setTab('Account')} className="mt-6 w-full rounded-xl bg-black py-3 text-xs font-black text-white">Manage profile</button></Panel></div></div>}
      {tab === 'Orders' && <Panel title="Order history" subtitle="Track purchases, review delivered products, and manage post-delivery support.">{orders.length ? <div className="space-y-4">{orders.map((order) => <OrderCard key={order._id} order={order} onReview={(itemIndex) => setReviewTarget({ order, itemIndex })} />)}</div> : <EmptyOrders />}</Panel>}
      {tab === 'Account' && <div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><Panel title="Profile photo"><div className="flex flex-col items-center py-5 text-center"><div className="flex h-32 w-32 items-center justify-center overflow-hidden rounded-4xl bg-black text-3xl font-black text-white">{user.photo ? <img src={user.photo} alt={user.name} className="h-full w-full object-cover" /> : initials}</div><button onClick={() => fileRef.current?.click()} disabled={uploading} className="mt-5 rounded-xl border border-gray-300 px-5 py-3 text-xs font-black text-black">{uploading ? 'Uploading…' : 'Choose a new photo'}</button><p className="mt-3 text-xs leading-5 text-gray-400">JPG, PNG, WebP or AVIF. Maximum 5MB.</p></div></Panel><Panel title="Personal information"><form onSubmit={saveProfile} className="space-y-4"><Field label="Full name" value={profile.name} onChange={(value) => setProfile({ ...profile, name: value })} required /><Field label="Email address" value={user.email} disabled /><Field label="Phone number" value={profile.phone} onChange={(value) => setProfile({ ...profile, phone: value })} placeholder="03XXXXXXXXX" /><button disabled={saving} className="rounded-xl bg-black px-6 py-3 text-xs font-black text-white disabled:opacity-50">{saving ? 'Saving…' : 'Save changes'}</button></form></Panel><section className="lg:col-span-2"><Panel title="Saved addresses" subtitle="Your default address is selected automatically during checkout.">{user.addresses?.length ? <div className="grid gap-3 md:grid-cols-2">{user.addresses.map((address) => <article key={address._id} className={`rounded-2xl border p-5 ${address.isDefault ? 'border-black bg-gray-50' : 'border-gray-200'}`}><div className="flex items-center justify-between"><b className="text-sm text-black">{address.label}</b>{address.isDefault && <span className="rounded-full bg-black px-2.5 py-1 text-[9px] font-black uppercase text-white">Default</span>}</div><p className="mt-3 text-sm leading-6 text-gray-600">{address.name} · {address.phone}<br />{address.address}<br />{address.city}, {address.province}</p>{!address.isDefault && <button onClick={() => makeDefault(address)} className="mt-4 text-xs font-black text-black underline">Set as default</button>}</article>)}</div> : <p className="py-8 text-center text-sm text-gray-400">No saved addresses yet. You can save one during checkout.</p>}</Panel></section></div>}
      {tab === 'Security' && <div className="mx-auto max-w-2xl"><Panel title="Change password" subtitle="Use a unique password with at least 8 characters. Google-only accounts can leave the current password blank."><form onSubmit={changePassword} className="space-y-4"><Field label="Current password" type="password" value={password.currentPassword} onChange={(value) => setPassword({ ...password, currentPassword: value })} required={!user.firebaseUid} /><Field label="New password" type="password" value={password.newPassword} onChange={(value) => setPassword({ ...password, newPassword: value })} required /><Field label="Confirm new password" type="password" value={password.confirmPassword} onChange={(value) => setPassword({ ...password, confirmPassword: value })} required /><button disabled={saving} className="w-full rounded-xl bg-black py-3.5 text-xs font-black text-white disabled:opacity-50">{saving ? 'Updating…' : user.firebaseUid ? 'Set or update password' : 'Update password'}</button></form></Panel></div>}
      {tab === 'Devices' && <DevicesPanel sessions={sessions} loading={sessionsLoading} endSession={endSession} />}
    </div>
    {reviewTarget && <ReviewModal target={reviewTarget} form={reviewForm} setForm={setReviewForm} submitting={reviewing} close={() => setReviewTarget(null)} submit={submitReview} />}
  </main>
}

const authHeaders = () => ({ Authorization: `Bearer ${getCustomerToken()}` })
function Panel({ title, subtitle, action, children }) { return <section className="rounded-3xl border border-gray-200 bg-white p-5 shadow-sm md:p-7"><div className="mb-5 flex items-start justify-between gap-4"><div><h2 className="text-lg font-black text-black">{title}</h2>{subtitle && <p className="mt-1 text-xs leading-5 text-gray-500">{subtitle}</p>}</div>{action}</div>{children}</section> }
function Stat({ label, value }) { return <div className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><p className="text-2xl font-black text-black">{value}</p><p className="mt-1 text-[10px] font-black uppercase tracking-wider text-gray-400">{label}</p></div> }
function Detail({ label, value }) { return <div className="flex justify-between gap-4 border-b border-gray-100 pb-3"><dt className="text-gray-400">{label}</dt><dd className="text-right font-bold text-black">{value}</dd></div> }
function Field({ label, value, onChange, type = 'text', ...props }) { return <label className="block text-xs font-black uppercase tracking-wide text-gray-500">{label}<input type={type} value={value} onChange={(event) => onChange?.(event.target.value)} className="mt-2 w-full rounded-xl border border-gray-300 bg-white px-4 py-3 text-sm font-medium normal-case text-black outline-none focus:border-black disabled:bg-gray-100 disabled:text-gray-500" {...props} /></label> }
function DevicesPanel({ sessions, loading, endSession }) { return <Panel title="Login devices" subtitle="See where your account is signed in and end any active session.">{loading ? <div className="py-12 text-center text-sm text-gray-400">Loading devices…</div> : <div className="space-y-3">{sessions.map((session) => <article key={session._id} className={`flex flex-col gap-4 rounded-2xl border p-4 sm:flex-row sm:items-center sm:justify-between ${session.isCurrent ? 'border-black bg-gray-50' : 'border-gray-200'}`}><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><b className="text-sm text-black">{session.device} · {session.browser}</b>{session.isCurrent && <span className="rounded-full bg-black px-2 py-1 text-[9px] font-black uppercase text-white">Current device</span>}<span className={`rounded-full px-2 py-1 text-[9px] font-black uppercase ${session.isActive ? 'bg-emerald-50 text-emerald-700' : 'bg-gray-100 text-gray-500'}`}>{session.isActive ? 'Active' : 'Signed out'}</span></div><p className="mt-2 text-xs text-gray-500">{session.context === 'admin' ? 'Admin portal' : 'Storefront'} · {session.ipAddress || 'IP unavailable'}</p><p className="mt-1 text-[11px] text-gray-400">Last active {new Date(session.lastSeenAt || session.createdAt).toLocaleString()}{session.loggedOutAt ? ` · Signed out ${new Date(session.loggedOutAt).toLocaleString()}` : ''}</p></div>{session.isActive && <button onClick={() => endSession(session)} className="shrink-0 rounded-xl border border-red-200 px-4 py-2.5 text-xs font-black text-red-600 hover:bg-red-50">{session.isCurrent ? 'Sign out here' : 'Sign out device'}</button>}</article>)}{!sessions.length && <p className="py-10 text-center text-sm text-gray-400">No login history is available yet.</p>}</div>}</Panel> }
function CompactOrder({ order }) { return <div className="flex flex-wrap items-center justify-between gap-3 py-4"><div><p className="text-sm font-black text-black">{order.orderNumber}</p><p className="mt-1 text-xs text-gray-400">{new Date(order.createdAt).toLocaleDateString()} · {order.items.length} item{order.items.length === 1 ? '' : 's'}</p></div><div className="text-right"><span className="rounded-full bg-gray-100 px-3 py-1 text-[10px] font-black capitalize text-gray-700">{order.status.replaceAll('-', ' ')}</span><p className="mt-2 text-sm font-black text-black">Rs. {order.total.toLocaleString()}</p></div></div> }
function OrderCard({ order, onReview }) { return <article className="overflow-hidden rounded-2xl border border-gray-200"><header className="flex flex-wrap items-center justify-between gap-3 bg-gray-50 px-5 py-4"><div><p className="text-sm font-black text-black">{order.orderNumber}</p><p className="mt-1 text-xs text-gray-400">Placed {new Date(order.createdAt).toLocaleDateString()}</p></div><div className="text-right"><span className="rounded-full bg-black px-3 py-1 text-[10px] font-black capitalize text-white">{order.status.replaceAll('-', ' ')}</span><p className="mt-2 text-sm font-black text-black">Rs. {order.total.toLocaleString()}</p></div></header><div className="divide-y divide-gray-100 px-5">{order.items.map((item, index) => <div key={`${item.productId}-${index}`} className="flex items-center gap-4 py-4"><img src={item.image || '/favicon.ico'} alt={item.name} className="h-16 w-16 rounded-xl bg-gray-100 object-cover" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-black text-black">{item.name}</p><p className="mt-1 text-xs text-gray-500">Size {item.selectedSize || '—'} · Qty {item.quantity}</p>{order.status === 'delivered' && item.product && <button onClick={() => onReview(index)} className="mt-2 text-[10px] font-black uppercase text-black underline">Write a review</button>}</div><b className="text-sm text-black">Rs. {(item.price * item.quantity).toLocaleString()}</b></div>)}</div></article> }
function EmptyOrders() { return <div className="py-12 text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-gray-100 text-2xl">◎</div><p className="mt-4 font-black text-black">No orders yet</p><Link href="/shop" className="mt-4 inline-flex rounded-xl bg-black px-5 py-3 text-xs font-black text-white">Start shopping</Link></div> }
function ReviewModal({ target, form, setForm, submitting, close, submit }) { return <div className="fixed inset-0 z-120 flex items-center justify-center bg-black/60 p-4 backdrop-blur-sm"><button className="absolute inset-0" onClick={close} aria-label="Close review" /><section className="relative w-full max-w-lg rounded-3xl bg-white p-7 shadow-2xl"><button onClick={close} className="absolute right-5 top-5 h-9 w-9 rounded-full bg-gray-100 text-xl">×</button><p className="text-[10px] font-black uppercase tracking-[.2em] text-gray-400">Verified purchase</p><h2 className="mt-2 pr-10 text-2xl font-black text-black">Review {target.order.items[target.itemIndex].name}</h2><div className="mt-6 flex gap-2">{[1,2,3,4,5].map((star) => <button key={star} onClick={() => setForm({ ...form, rating: star })} className={`text-3xl ${star <= form.rating ? 'text-amber-400' : 'text-gray-200'}`}>★</button>)}</div><textarea value={form.comment} onChange={(event) => setForm({ ...form, comment: event.target.value })} rows={5} placeholder="Share your thoughts on quality, fit, and overall experience." className="mt-5 w-full rounded-2xl border border-gray-300 p-4 text-sm text-black outline-none focus:border-black" /><button disabled={submitting} onClick={submit} className="mt-4 w-full rounded-xl bg-black py-3.5 text-sm font-black text-white disabled:opacity-50">{submitting ? 'Publishing…' : 'Publish review'}</button></section></div> }
