'use client'

import { useEffect, useRef, useState } from 'react'
import { Plus, Trash2, UploadCloud } from 'lucide-react'
import AdminShell, { Notice } from '@/components/AdminShell'
import { api } from '@/lib/api'

const regions = ['Islamabad Capital Territory', 'Punjab', 'Sindh', 'Khyber Pakhtunkhwa', 'Balochistan', 'Azad Jammu and Kashmir', 'Gilgit-Baltistan']
const defaultStore = { name: 'Komrez', currency: 'PKR', freeShippingThreshold: 2000, flatShipping: 250, shippingRates: { 'Islamabad Capital Territory': 180, Punjab: 220, Sindh: 250, 'Khyber Pakhtunkhwa': 280, Balochistan: 350, 'Azad Jammu and Kashmir': 320, 'Gilgit-Baltistan': 400 } }
const defaultPayments = [{ id: 'cod', name: 'Cash on Delivery', type: 'cod', enabled: true, instructions: 'Pay when your order arrives.' }]
const defaultSlides = [{ id: '1', title: 'New Collection is Here', subtitle: 'Street Style Redefined', buttonText: 'Shop Now', buttonLink: '/shop', image: '/images/banners/banner2.jpg' }]

export default function SettingsPage() {
  const [store, setStore] = useState(defaultStore), [payments, setPayments] = useState(defaultPayments), [slides, setSlides] = useState(defaultSlides)
  const [message, setMessage] = useState(''), [error, setError] = useState(''), fileRef = useRef(null), [uploadIndex, setUploadIndex] = useState(0)
  useEffect(() => { api('/admin/settings').then(({ data }) => { const map = Object.fromEntries(data.map((item) => [item.key, item.value])); if (map.store) setStore({ ...defaultStore, ...map.store, shippingRates: { ...defaultStore.shippingRates, ...map.store.shippingRates } }); if (map.payments?.methods) setPayments(map.payments.methods); if (map.hero?.slides) setSlides(map.hero.slides) }).catch((requestError) => setError(requestError.message)) }, [])
  const save = async (event) => { event.preventDefault(); setError(''); setMessage(''); try { await Promise.all([api('/admin/settings/store', { method: 'PUT', body: JSON.stringify({ value: { ...store, freeShippingThreshold: Number(store.freeShippingThreshold), flatShipping: Number(store.flatShipping), shippingRates: Object.fromEntries(Object.entries(store.shippingRates || {}).map(([key, value]) => [key, Number(value)])) } }) }), api('/admin/settings/payments', { method: 'PUT', body: JSON.stringify({ value: { methods: payments } }) }), api('/admin/settings/hero', { method: 'PUT', body: JSON.stringify({ value: { slides } }) })]); setMessage('Store, shipping, payment and hero settings saved.') } catch (requestError) { setError(requestError.message) } }
  const updatePayment = (index, key, value) => setPayments((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item))
  const updateSlide = (index, key, value) => setSlides((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item))
  const uploadHero = async (files) => { if (!files?.[0]) return; const body = new FormData(); body.append('images', files[0]); try { const { data } = await api('/uploads/products', { method: 'POST', body }); updateSlide(uploadIndex, 'image', data[0].url) } catch (requestError) { setError(requestError.message) } }
  return <AdminShell title="Store settings" description="Control storefront, payments and homepage content.">{error && <Notice>{error}</Notice>}{message && <Notice type="success">{message}</Notice>}<form onSubmit={save} className="mt-4 space-y-6">
    <Section title="General store"><div className="grid gap-4 sm:grid-cols-2"><Field label="Store name" value={store.name} onChange={(value) => setStore({ ...store, name: value })} /><Field label="Currency" value={store.currency} onChange={(value) => setStore({ ...store, currency: value })} /><Field label="Free shipping threshold" type="number" value={store.freeShippingThreshold} onChange={(value) => setStore({ ...store, freeShippingThreshold: value })} /><Field label="Fallback shipping charge" type="number" value={store.flatShipping} onChange={(value) => setStore({ ...store, flatShipping: value })} /></div></Section>
    <Section title="Pakistan shipping rates"><p className="mb-4 text-sm text-gray-500">These charges apply below the free-shipping threshold and are calculated from the customer&apos;s province.</p><div className="grid gap-4 sm:grid-cols-2">{regions.map((region) => <Field key={region} label={region} type="number" value={store.shippingRates?.[region] ?? defaultStore.shippingRates[region]} onChange={(value) => setStore({ ...store, shippingRates: { ...defaultStore.shippingRates, ...store.shippingRates, [region]: value } })} />)}</div></Section>
    <Section title="Payment methods" action={<button type="button" onClick={() => setPayments([...payments, { id: `bank-${Date.now()}`, name: 'Bank Transfer', type: 'bank', enabled: true, accountTitle: '', accountNumber: '', bankName: '', instructions: '' }])} className="flex items-center gap-2 rounded-xl border px-3 py-2 text-xs font-bold"><Plus size={14} />Add method</button>}>{payments.map((method, index) => <div key={method.id} className="mb-4 grid gap-3 rounded-2xl bg-gray-50 p-4 sm:grid-cols-2"><Field label="Display name" value={method.name} onChange={(value) => updatePayment(index, 'name', value)} /><label className="text-xs font-bold uppercase text-gray-500">Type<select value={method.type} onChange={(e) => updatePayment(index, 'type', e.target.value)} className="input"><option value="cod">Cash on delivery</option><option value="bank">Bank transfer</option><option value="easypaisa">EasyPaisa</option><option value="jazzcash">JazzCash</option></select></label>{method.type !== 'cod' && <><Field label="Bank / wallet name" value={method.bankName || ''} onChange={(value) => updatePayment(index, 'bankName', value)} /><Field label="Account title" value={method.accountTitle || ''} onChange={(value) => updatePayment(index, 'accountTitle', value)} /><Field label="Account number" value={method.accountNumber || ''} onChange={(value) => updatePayment(index, 'accountNumber', value)} /></>}<Field label="Instructions" value={method.instructions || ''} onChange={(value) => updatePayment(index, 'instructions', value)} /><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={method.enabled} onChange={(e) => updatePayment(index, 'enabled', e.target.checked)} />Enabled</label>{payments.length > 1 && <button type="button" onClick={() => setPayments(payments.filter((_, itemIndex) => itemIndex !== index))} className="flex items-center gap-2 text-xs font-bold text-red-500"><Trash2 size={14} />Remove</button>}</div>)}</Section>
    <Section title="Homepage hero slides" action={<button type="button" onClick={() => setSlides([...slides, { id: String(Date.now()), title: '', subtitle: '', buttonText: 'Shop Now', buttonLink: '/shop', image: '' }])} className="flex items-center gap-2 rounded-xl border px-3 py-2 text-xs font-bold"><Plus size={14} />Add slide</button>}>{slides.map((slide, index) => <div key={slide.id} className="mb-4 grid gap-3 rounded-2xl bg-gray-50 p-4 sm:grid-cols-2"><Field label="Title" value={slide.title} onChange={(value) => updateSlide(index, 'title', value)} /><Field label="Subtitle" value={slide.subtitle} onChange={(value) => updateSlide(index, 'subtitle', value)} /><Field label="Button text" value={slide.buttonText} onChange={(value) => updateSlide(index, 'buttonText', value)} /><Field label="Button link" value={slide.buttonLink} onChange={(value) => updateSlide(index, 'buttonLink', value)} /><Field label="Image URL" value={slide.image} onChange={(value) => updateSlide(index, 'image', value)} /><button type="button" onClick={() => { setUploadIndex(index); fileRef.current?.click() }} className="mt-5 flex items-center justify-center gap-2 rounded-xl border bg-white text-sm font-bold"><UploadCloud size={16} />Upload hero image</button>{slides.length > 1 && <button type="button" onClick={() => setSlides(slides.filter((_, itemIndex) => itemIndex !== index))} className="flex items-center gap-2 text-xs font-bold text-red-500"><Trash2 size={14} />Remove slide</button>}</div>)}<input ref={fileRef} hidden type="file" accept="image/*" onChange={(e) => uploadHero(e.target.files)} /></Section>
    <button className="rounded-xl bg-black px-7 py-3 text-xs font-black uppercase text-white">Save all settings</button></form></AdminShell>
}

function Section({ title, action, children }) { return <section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-black">{title}</h2>{action}</div>{children}</section> }
function Field({ label, value, onChange, type = 'text' }) { return <label className="text-xs font-bold uppercase text-gray-500">{label}<input type={type} value={value} onChange={(e) => onChange(e.target.value)} className="input" /></label> }
