'use client'

import { useCallback, useEffect, useRef, useState } from 'react'
import { Archive, ImagePlus, LoaderCircle, Pencil, Plus, RotateCcw, Trash2, UploadCloud, X } from 'lucide-react'
import AdminShell, { Empty, Notice } from '@/components/AdminShell'
import { api } from '@/lib/api'
import { useAdminModal } from '@/components/ModalProvider'
import { toast } from '@/components/ToastProvider'

const sizeOptions = ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL', 'One Size']
const blank = { name: '', purchasePrice: '', regularPrice: '', salePrice: '', isOnSale: false, category: '', gender: 'unisex', image: '', images: [], sizes: [], stock: 0, description: '', badge: '', isFeatured: false }
const money = (value) => Number(value || 0)

export default function ProductsPage() {
  const { confirm } = useAdminModal()
  const [products, setProducts] = useState([]), [categories, setCategories] = useState([]), [form, setForm] = useState(blank)
  const [editing, setEditing] = useState(null), [open, setOpen] = useState(false), [message, setMessage] = useState('')
  const [uploading, setUploading] = useState(false), [saving, setSaving] = useState(false)
  const fileRef = useRef(null)
  const load = useCallback(() => Promise.all([api('/products?includeInactive=true&limit=100'), api('/categories')]).then(([productResult, categoryResult]) => { setProducts(productResult.data); setCategories(categoryResult.data) }).catch((error) => setMessage(error.message)), [])
  useEffect(() => { load() }, [load])

  const openNew = () => { setEditing(null); setForm({ ...blank, category: categories[0]?.slug || '' }); setOpen(true) }
  const edit = (product) => { const images = [...new Set([product.image, ...(product.images || [])].filter(Boolean))]; setEditing(product._id); setForm({ ...product, images, regularPrice: product.isOnSale ? product.originalPrice : product.price, salePrice: product.isOnSale ? product.price : '' }); setOpen(true) }
  const uploadImages = async (files) => { const selected = [...files].slice(0, Math.max(0, 8 - form.images.length)); if (!selected.length) return; setUploading(true); try { const body = new FormData(); selected.forEach((file) => body.append('images', file)); const { data } = await api('/uploads/products', { method: 'POST', body }); const urls = data.map((item) => item.url); setForm((current) => ({ ...current, images: [...current.images, ...urls], image: current.image || urls[0] })) } catch (error) { setMessage(error.message) } finally { setUploading(false) } }
  const removeImage = (url) => setForm((current) => { const images = current.images.filter((item) => item !== url); return { ...current, images, image: current.image === url ? images[0] || '' : current.image } })
  const toggleSize = (size) => setForm((current) => ({ ...current, sizes: current.sizes.includes(size) ? current.sizes.filter((item) => item !== size) : [...current.sizes, size] }))
  const save = async (event) => { event.preventDefault(); setMessage(''); if (!form.image) return setMessage('Upload at least one product image.'); if (!form.category) return setMessage('Select a category.'); if (form.isOnSale && (!money(form.salePrice) || money(form.salePrice) >= money(form.regularPrice))) return setMessage('Sale price must be lower than the regular selling price.'); setSaving(true)
    const payload = { ...form, purchasePrice: money(form.purchasePrice), price: form.isOnSale ? money(form.salePrice) : money(form.regularPrice), originalPrice: form.isOnSale ? money(form.regularPrice) : 0, stock: Number(form.stock), badge: form.isOnSale ? (form.badge || 'SALE') : form.badge }
    delete payload.regularPrice; delete payload.salePrice
    try { await api(editing ? `/products/${editing}` : '/products', { method: editing ? 'PATCH' : 'POST', body: JSON.stringify(payload) }); toast('success', `${form.name} has been saved.`); setOpen(false); await load() } catch (error) { setMessage(error.message) } finally { setSaving(false) }
  }
  const archive = async (id) => { if (!await confirm({ title: 'Archive product?', message: 'The product will be hidden from the storefront and can be restored later.', confirmText: 'Archive', tone: 'danger' })) return; await api(`/products/${id}`, { method: 'DELETE' }); await load() }
  const restore = async (id) => { await api(`/products/${id}`, { method: 'PATCH', body: JSON.stringify({ isActive: true }) }); toast('success', 'Product has been restored.'); await load() }
  const permanentDelete = async (id) => { if (!await confirm({ title: 'Delete product permanently?', message: 'Order snapshots will remain, but the catalog product cannot be recovered.', confirmText: 'Delete permanently', tone: 'danger' })) return; await api(`/products/${id}?permanent=true`, { method: 'DELETE' }); await load() }

  return <AdminShell title="Products" description="Manage product costs, selling prices, sales, images and stock." actions={<button onClick={openNew} className="flex items-center gap-2 rounded-xl bg-black px-4 py-2.5 text-xs font-black uppercase tracking-wider text-white"><Plus size={16} />Add product</button>}>
    {message && <Notice>{message}</Notice>}
    <div className="mt-4 overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-225 text-left"><thead className="bg-gray-50 text-[10px] uppercase tracking-wider text-gray-400"><tr><th className="p-4">Product</th><th>Category</th><th>Cost</th><th>Selling price</th><th>Stock</th><th>Status</th><th className="p-4 text-right">Actions</th></tr></thead><tbody className="divide-y">{products.map((product) => <tr key={product._id}><td className="p-4"><div className="flex items-center gap-3"><img src={product.image} alt={product.name} className="h-12 w-12 rounded-xl object-cover" /><div><p className="text-sm font-bold">{product.name}</p>{product.isOnSale && <span className="text-[10px] font-bold text-red-500">ON SALE</span>}</div></div></td><td className="text-sm capitalize">{product.category}</td><td className="text-sm">Rs. {money(product.purchasePrice).toLocaleString()}</td><td><p className="text-sm font-bold">Rs. {product.price.toLocaleString()}</p>{product.isOnSale && <p className="text-xs text-gray-400 line-through">Rs. {product.originalPrice.toLocaleString()}</p>}</td><td className={`text-sm font-bold ${product.stock <= 5 ? 'text-red-600' : ''}`}>{product.stock}{product.stock <= 5 && <span className="ml-1 text-[9px]">LOW</span>}</td><td><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${product.isActive ? 'bg-green-50 text-green-700' : 'bg-gray-100 text-gray-500'}`}>{product.isActive ? 'Active' : 'Archived'}</span></td><td className="p-4 text-right"><button aria-label={`Edit ${product.name}`} onClick={() => edit(product)} className="rounded-lg p-2 hover:bg-gray-100"><Pencil size={16} /></button>{product.isActive ? <button aria-label={`Archive ${product.name}`} onClick={() => archive(product._id)} className="rounded-lg p-2 text-orange-600 hover:bg-orange-50"><Archive size={16} /></button> : <button aria-label={`Restore ${product.name}`} onClick={() => restore(product._id)} className="rounded-lg p-2 text-green-700 hover:bg-green-50"><RotateCcw size={16} /></button>}<button aria-label={`Delete ${product.name} permanently`} onClick={() => permanentDelete(product._id)} className="rounded-lg p-2 text-red-600 hover:bg-red-50"><Trash2 size={16} /></button></td></tr>)}</tbody></table>{!products.length && <Empty>No products found.</Empty>}</div>

    {open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4"><form onSubmit={save} className="max-h-[94vh] w-full max-w-3xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-[10px] font-bold uppercase tracking-widest text-gray-400">Catalog editor</p><h2 className="text-xl font-black">{editing ? 'Edit product' : 'Add product'}</h2></div><button type="button" aria-label="Close" onClick={() => setOpen(false)} className="rounded-full bg-gray-100 p-2"><X size={18} /></button></div>
      <div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Product name"><input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="input" /></Field><Field label="Category"><select required value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} className="input"><option value="">Select category</option>{categories.map((category) => <option key={category._id} value={category.slug}>{category.name}</option>)}</select></Field>
        <Field label="Purchase price / cost"><input required min="0" type="number" value={form.purchasePrice} onChange={(e) => setForm({ ...form, purchasePrice: e.target.value })} className="input" /></Field><Field label="Regular selling price"><input required min="0" type="number" value={form.regularPrice} onChange={(e) => setForm({ ...form, regularPrice: e.target.value })} className="input" /></Field>
        <div className="sm:col-span-2 rounded-2xl border bg-gray-50 p-4"><label className="flex items-center justify-between gap-4"><span><b className="block text-sm">Put this product on sale</b><span className="text-xs text-gray-500">Storefront will show the regular price crossed out.</span></span><input type="checkbox" checked={form.isOnSale} onChange={(e) => setForm({ ...form, isOnSale: e.target.checked })} className="h-5 w-5" /></label>{form.isOnSale && <label className="mt-4 block text-xs font-bold uppercase text-gray-500">Sale price<input required min="0" type="number" value={form.salePrice} onChange={(e) => setForm({ ...form, salePrice: e.target.value })} className="input" /></label>}</div>
        <Field label="Department"><div className="mt-1 grid grid-cols-3 gap-2">{['men','women','unisex'].map((gender) => <button type="button" key={gender} onClick={() => setForm({ ...form, gender })} className={`rounded-xl border px-3 py-3 text-xs font-bold uppercase ${form.gender === gender ? 'border-black bg-black text-white' : 'bg-white'}`}>{gender}</button>)}</div></Field><Field label="Stock quantity"><input required min="0" type="number" value={form.stock} onChange={(e) => setForm({ ...form, stock: e.target.value })} className="input" /></Field>
        <div className="sm:col-span-2"><span className="text-xs font-bold uppercase text-gray-500">Available sizes</span><div className="mt-2 flex flex-wrap gap-2">{sizeOptions.map((size) => <button type="button" key={size} onClick={() => toggleSize(size)} className={`rounded-xl border px-4 py-2 text-xs font-bold ${form.sizes.includes(size) ? 'border-black bg-black text-white' : 'bg-white'}`}>{size}</button>)}</div></div>
        <div className="sm:col-span-2"><span className="text-xs font-bold uppercase text-gray-500">Product images (up to 8)</span><button type="button" onClick={() => fileRef.current?.click()} onDrop={(e) => { e.preventDefault(); uploadImages(e.dataTransfer.files) }} onDragOver={(e) => e.preventDefault()} className="mt-2 flex w-full flex-col items-center rounded-2xl border-2 border-dashed p-6 text-gray-500">{uploading ? <LoaderCircle className="animate-spin" /> : <UploadCloud />}<b className="mt-2 text-sm">{uploading ? 'Uploading…' : 'Choose or drop multiple images'}</b></button><input ref={fileRef} hidden multiple accept="image/jpeg,image/png,image/webp,image/avif" type="file" onChange={(e) => uploadImages(e.target.files)} />{!!form.images.length && <div className="mt-3 grid grid-cols-4 gap-3 sm:grid-cols-6">{form.images.map((url) => <div key={url} className={`relative overflow-hidden rounded-xl border-2 ${form.image === url ? 'border-black' : 'border-transparent'}`}><button type="button" onClick={() => setForm({ ...form, image: url })} className="aspect-square w-full"><img src={url} alt="Product preview" className="h-full w-full object-cover" /></button><button type="button" aria-label="Remove image" onClick={() => removeImage(url)} className="absolute right-1 top-1 rounded-full bg-white p-1"><X size={12} /></button></div>)}</div>}</div>
        <Field label="Image URL" wide><div className="mt-1 flex gap-2"><input id="product-image-url" placeholder="https://…" className="input mt-0" /><button type="button" aria-label="Add image URL" onClick={() => { const input = document.getElementById('product-image-url'); const url = input.value.trim(); if (url) { setForm({ ...form, image: form.image || url, images: [...new Set([...form.images, url])] }); input.value = '' } }} className="rounded-xl border px-4"><ImagePlus size={18} /></button></div></Field>
        <Field label="Badge"><input value={form.badge} onChange={(e) => setForm({ ...form, badge: e.target.value })} placeholder="NEW, LIMITED…" className="input" /></Field><label className="flex items-center gap-2 pt-7 text-sm font-bold"><input type="checkbox" checked={form.isFeatured} onChange={(e) => setForm({ ...form, isFeatured: e.target.checked })} />Featured on homepage</label><Field label="Description" wide><textarea rows={4} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="input" /></Field>
      </div><button disabled={saving || uploading} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-black py-3 text-sm font-black uppercase text-white disabled:opacity-50">{saving && <LoaderCircle size={17} className="animate-spin" />}{saving ? 'Saving…' : 'Save product'}</button></form></div>}
  </AdminShell>
}

function Field({ label, wide, children }) { return <label className={wide ? 'sm:col-span-2' : ''}><span className="text-xs font-bold uppercase text-gray-500">{label}</span>{children}</label> }
